#!/usr/bin/env node
// Writes, and with --check verifies, everything a tool needs to read the development agents
// defined in .agents/agents/<name>.md (ADR 0038). Dependency-free: node:fs and node:path only.
//
//   node tools/agents/sync.mjs            write the links and adapters, delete the ones that lost their agent
//   node tools/agents/sync.mjs --check    change nothing; exit 1 on any drift (CI runs this)
//
// Links (relative symlinks to the canonical file):
//   .claude/agents/<name>.md   Claude Code (and Cursor)
//   .opencode/agents/<name>.md OpenCode
// Adapters (generated files that point at the canonical file, never copy it):
//   .kiro/agents/<name>.json   Kiro CLI: "prompt" is a file:// URI relative to the adapter
//   .codex/agents/<name>.toml  Codex (not for a primary agent)
//   .gemini/agents/<name>.md   Gemini CLI (not for a primary agent); a regular file, Gemini skips symlinks
// Goose reads .agents/agents/ itself, so nothing is generated for it.
//
// Every file in those five directories is owned by this script. A file it did not generate is an error.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const AGENTS = '.agents/agents';
const SKILLS = '.agents/skills';
const SKILL_MIRRORS = ['.claude/skills', '.goose/skills', '.kiro/skills'];
const LINK_DIRS = ['.claude/agents', '.opencode/agents'];
const ADAPTER_DIRS = ['.kiro/agents', '.codex/agents', '.gemini/agents'];
const OWNED_DIRS = [...LINK_DIRS, ...ADAPTER_DIRS];
const ALLOWED_KEYS = new Set(['name', 'description', 'mode', 'skills', 'readonly', 'disallowedTools', 'permission']);
const FORBIDDEN_KEYS = new Set(['tools', 'model', 'color']);
const MODES = new Set(['primary', 'subagent', 'all']);
const MARK = 'Generated by tools/agents/sync.mjs';

const check = process.argv.includes('--check');
const problems = [];
const bad = (file, reason) => problems.push(`${file}: ${reason}`);
const abs = (rel) => path.join(ROOT, rel);
const lstat = (rel) => { try { return fs.lstatSync(abs(rel)); } catch { return null; } };

// ---- parse and validate the canonical files --------------------------------------------------

function parse(rel, text) {
  const lines = text.split('\n');
  if (lines[0] !== '---') { bad(rel, 'must start with a --- frontmatter line'); return null; }
  const end = lines.indexOf('---', 1);
  if (end < 0) { bad(rel, 'frontmatter is not closed by ---'); return null; }
  const meta = {};
  let cur = null;
  for (const line of lines.slice(1, end)) {
    const m = /^([A-Za-z][\w-]*):\s*(.*)$/.exec(line);
    if (m) {
      const [, key, rest] = m;
      if (key in meta) bad(rel, `duplicate key ${key}`);
      cur = key;
      if (rest === '') meta[key] = { list: [], bare: true };
      else meta[key] = { raw: rest, value: rest.startsWith('"') ? safeJson(rest) : rest.trim() };
    } else if (cur && meta[cur]?.bare) {
      const item = /^\s+-\s+(.+)$/.exec(line);
      if (item) meta[cur].list.push(item[1].trim()); // indented maps (permission) are skipped
    }
  }
  return { meta, body: lines.slice(end + 1).join('\n') };
}

function safeJson(raw) { try { return JSON.parse(raw); } catch { return undefined; } }

function skillResolves(rel, name) {
  if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) return bad(rel, `skill name ${name} is not a skill name`);
  if (!fs.existsSync(abs(`${SKILLS}/${name}/SKILL.md`))) return bad(rel, `skill ${name}: ${SKILLS}/${name}/SKILL.md does not exist`);
  for (const mirror of SKILL_MIRRORS) {
    const p = abs(`${mirror}/${name}`);
    let ok = false;
    try { ok = fs.realpathSync(p) === fs.realpathSync(abs(`${SKILLS}/${name}`)); } catch { /* missing */ }
    if (!ok) bad(rel, `skill ${name}: ${mirror}/${name} does not resolve to ${SKILLS}/${name}`);
  }
}

function load() {
  const dir = abs(AGENTS);
  const files = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => !f.startsWith('.')).sort() : [];
  const agents = [];
  for (const f of files) {
    const rel = `${AGENTS}/${f}`;
    if (!/^[a-z0-9][a-z0-9-]*\.md$/.test(f)) { bad(rel, 'file name must match ^[a-z0-9][a-z0-9-]*\\.md$'); continue; }
    if (!lstat(rel)?.isFile()) { bad(rel, 'must be a regular file'); continue; }
    const parsed = parse(rel, fs.readFileSync(abs(rel), 'utf8'));
    if (!parsed) continue;
    const { meta, body } = parsed;
    const stem = f.slice(0, -3);
    for (const k of Object.keys(meta)) {
      if (FORBIDDEN_KEYS.has(k)) bad(rel, `frontmatter key ${k} is forbidden (ADR 0038): it breaks another tool`);
      else if (!ALLOWED_KEYS.has(k)) bad(rel, `frontmatter key ${k} is not in the portable set`);
    }
    if (meta.name?.value !== stem) bad(rel, `name must equal the file name (${stem})`);
    if (!meta.description?.raw?.startsWith('"') || !meta.description.value) bad(rel, 'description must be a non-empty double-quoted string');
    if (!MODES.has(meta.mode?.value)) bad(rel, 'mode must be primary, subagent or all');
    if (meta.readonly && meta.readonly.value !== 'true') bad(rel, 'readonly, if present, must be true');
    if (meta.disallowedTools && meta.disallowedTools.value === undefined) bad(rel, 'disallowedTools must be a comma-separated string on one line, not a YAML list');
    const skills = meta.skills?.list ?? [];
    if (meta.skills && !meta.skills.bare) bad(rel, 'skills must be a YAML list');
    skills.forEach((s) => skillResolves(rel, s));
    if (/\]\((?!https?:|mailto:|#)[^)\s]+\)/.test(body)) bad(rel, 'the body has a relative Markdown link; cite paths as code spans');
    const section = /^## Skills\s*$([\s\S]*?)(?=^## |(?![\s\S]))/m.exec(body);
    if (!section) bad(rel, 'the body needs a "## Skills" section');
    else [...section[1].matchAll(/`([^`]+)`/g)].forEach((m) => skillResolves(rel, m[1]));
    agents.push({
      name: stem,
      description: meta.description?.value ?? '',
      mode: meta.mode?.value,
      readonly: meta.readonly?.value === 'true',
      editsDenied: (meta.disallowedTools?.value ?? '').split(',').map((s) => s.trim()).includes('Edit'),
    });
  }
  return agents;
}

// ---- the expected tree -----------------------------------------------------------------------

function pointer(a) {
  const file = `${AGENTS}/${a.name}.md`;
  return `You are the \`${a.name}\` agent of this repository. Your instructions are the body of \`${file}\`, below its YAML frontmatter, a path from the repository root. Read that whole file now and follow it as your instructions. The agent guide \`CLAUDE.md\` (also \`AGENTS.md\`) still applies and its Invariants win. A skill it names is \`${SKILLS}/<name>/SKILL.md\`.`;
}

function kiro(a, all) {
  const tools = a.readonly ? ['read', 'grep', 'glob', 'shell', 'web_fetch', 'web_search']
    : a.editsDenied ? ['read', 'grep', 'glob', 'shell'] : ['*'];
  const json = {
    allowedTools: ['read', 'grep', 'glob'],
    description: a.description,
    name: a.name,
    prompt: `file://../../${AGENTS}/${a.name}.md`,
    tools,
  };
  const delegates = a.mode === 'primary' ? all.filter((o) => o.name !== a.name)
    : a.mode === 'all' ? all.filter((o) => o.mode === 'subagent') : [];
  if (delegates.length) json.toolsSettings = { subagent: { availableAgents: delegates.map((o) => o.name) } };
  return JSON.stringify(json, null, 2) + '\n';
}

const codex = (a) => `# ${MARK} from ${AGENTS}/${a.name}.md. Edit that file, then run: node tools/agents/sync.mjs
name = ${JSON.stringify(a.name)}
description = ${JSON.stringify(a.description)}
${a.readonly ? 'sandbox_mode = "read-only"\n' : a.editsDenied ? 'sandbox_mode = "workspace-write"\n' : ''}developer_instructions = """
${pointer(a)}
"""
`;

const gemini = (a) => `---
name: ${a.name}
description: ${JSON.stringify(a.description)}
kind: local
---
${pointer(a)}

${MARK} from \`${AGENTS}/${a.name}.md\`. Edit that file, then run \`node tools/agents/sync.mjs\`.
`;

function expected(agents) {
  const links = [];
  const adapters = [];
  for (const a of agents) {
    for (const d of LINK_DIRS) links.push({ rel: `${d}/${a.name}.md`, target: `../../${AGENTS}/${a.name}.md`, canon: `${AGENTS}/${a.name}.md` });
    adapters.push({ rel: `.kiro/agents/${a.name}.json`, text: kiro(a, agents) });
    if (a.mode !== 'primary') {
      adapters.push({ rel: `.codex/agents/${a.name}.toml`, text: codex(a) });
      adapters.push({ rel: `.gemini/agents/${a.name}.md`, text: gemini(a) });
    }
  }
  return { links, adapters };
}

// ---- ownership -------------------------------------------------------------------------------

function owned(rel) {
  const st = lstat(rel);
  if (!st) return false;
  if (st.isSymbolicLink()) return fs.readlinkSync(abs(rel)).startsWith(`../../${AGENTS}/`);
  if (!st.isFile()) return false;
  const text = fs.readFileSync(abs(rel), 'utf8');
  if (rel.endsWith('.json')) { try { return String(JSON.parse(text).prompt).startsWith(`file://../../${AGENTS}/`); } catch { return false; } }
  return text.includes(MARK);
}

// ---- run -------------------------------------------------------------------------------------

const agents = load();
const { links, adapters } = expected(agents);
const want = new Set([...links.map((l) => l.rel), ...adapters.map((a) => a.rel)]);

for (const l of links) {
  const st = lstat(l.rel);
  const fine = st?.isSymbolicLink() && fs.readlinkSync(abs(l.rel)) === l.target;
  if (fine) {
    let ok = false;
    try { ok = fs.realpathSync(abs(l.rel)) === fs.realpathSync(abs(l.canon)); } catch { /* dangling */ }
    if (!ok) bad(l.rel, `does not resolve to ${l.canon}`);
  } else if (check) {
    bad(l.rel, !st ? 'missing link' : !st.isSymbolicLink() ? 'is not a symlink' : `points to ${fs.readlinkSync(abs(l.rel))}, want ${l.target}`);
  } else if (st && !owned(l.rel)) {
    bad(l.rel, 'exists and is not a link this script owns; not overwritten');
  } else {
    fs.mkdirSync(path.dirname(abs(l.rel)), { recursive: true });
    if (st) fs.unlinkSync(abs(l.rel));
    fs.symlinkSync(l.target, abs(l.rel));
  }
}

for (const a of adapters) {
  const st = lstat(a.rel);
  const same = st?.isFile() && fs.readFileSync(abs(a.rel), 'utf8') === a.text;
  if (same) continue;
  if (check) bad(a.rel, !st ? 'missing adapter' : st.isFile() ? 'differs from the generated adapter; run node tools/agents/sync.mjs' : 'must be a regular file, not a link');
  else if (st && !owned(a.rel)) bad(a.rel, 'exists and is not a file this script generated; not overwritten');
  else {
    fs.mkdirSync(path.dirname(abs(a.rel)), { recursive: true });
    if (st) fs.unlinkSync(abs(a.rel));
    fs.writeFileSync(abs(a.rel), a.text);
  }
}

for (const d of OWNED_DIRS) {
  if (!fs.existsSync(abs(d))) continue;
  for (const f of fs.readdirSync(abs(d)).sort()) {
    const rel = `${d}/${f}`;
    if (want.has(rel)) continue;
    if (!owned(rel)) bad(rel, 'not generated by this script; these directories are generated-only (ADR 0038)');
    else if (check) bad(rel, 'orphan: its agent in .agents/agents is gone or no longer needs this file');
    else fs.rmSync(abs(rel));
  }
}

if (problems.length) {
  for (const p of problems) console.error(p);
  process.exit(1);
}
console.log(`${agents.length} agents, ${links.length} links, ${adapters.length} adapters ${check ? 'checked' : 'written'}`);
